# Generated by Django 5.0.1 on 2024-02-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_word_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('words', models.ManyToManyField(to='home.word')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.word')),
            ],
            options={
                'unique_together': {('word', 'response')},
            },
        ),
    ]
