# Generated by Django 5.0.1 on 2024-02-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_webpage_image_link'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='webpage',
        #     name='image_link',
        #     field=models.URLField(blank=True, null=True),
        # ),
    ]
