# Generated by Django 5.0.1 on 2024-02-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_webpage_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresponse',
            name='response',
            field=models.TextField(),
        ),
    ]
