# Generated by Django 5.0.1 on 2024-02-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_searchresponse_response'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchresponse',
            unique_together=set(),
        ),
    ]
