# Generated by Django 5.0.1 on 2024-02-23 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_searchresponse_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.word')),
            ],
        ),
    ]
