# Generated by Django 5.0.1 on 2024-02-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_indexqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
