# Generated by Django 5.0.1 on 2024-02-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_webpage_text_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='searchresponse',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
