# Generated by Django 5.0.1 on 2024-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_searchresponse_response_searchresponse_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='searchresponse',
            name='link',
        ),
        migrations.AddField(
            model_name='searchresponse',
            name='link',
            field=models.ManyToManyField(to='home.webpage'),
        ),
    ]
