# Generated by Django 5.0.1 on 2024-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_webpage_image_link_remove_webpage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='status',
            field=models.CharField(default='started', max_length=100),
        ),
    ]
