# Generated by Django 5.0.1 on 2024-02-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_webpage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='source',
            field=models.CharField(choices=[('DhivehiNLP', 'Dhivehi_NLP'), ('radheef.mv', 'radheef_mv')], default='DhivehiNLP', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('nan', 'nan'), ('kan', 'kan'), ('nan ithuru', 'nan_ithuru'), ('kan ithuru', 'kan_ithuru'), ('masdharu', 'masdharu'), ('nan ithuruge nan', 'nan_ithuruge_nan'), ('ithuru', 'ithuru'), ('akuru', 'akuru')], max_length=100, null=True),
        ),
    ]
