# Generated by Django 5.0.1 on 2024-02-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_partofspeech_remove_word_category_word_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezzon', models.CharField(blank=True, max_length=100, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
