# Generated by Django 5.0.1 on 2024-02-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_searchmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmanager',
            name='sezzon',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
