# Generated by Django 5.0.1 on 2024-03-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_searchmanager_sezzon'),
    ]

    operations = [
        # migrations.RunSQL(
        #     "UPDATE django_site SET domain='radheefu.com', name='RADHEEFU' WHERE id=1;"
        # )
    ]
